### ISSUE TITLE
Installation problems when Qt is not installed

### ISSUE THREAD

**Issue by theowiik** [albin-johansson/tactile#30]
I could not install it, it said that Qt5Widgets.dll was missing. 
![iNuGUATzVw](https://user-images.githubusercontent.com/42991003/102236986-6e653180-3ef4-11eb-9418-ee5a171946a7.png)

After I manually added it, it showed the following error:
![bild](https://user-images.githubusercontent.com/42991003/102237113-95236800-3ef4-11eb-9559-6791ad2bc16f.png)

**Comment by albin-johansson** [comment]
Oh crap! The `.dll` is a silly mistake, but I don't know how to fix platform plugin path for now. Will look into this. Thank you for the issue Theo! 😄

**Comment by theowiik** [comment]
Hello Albin!

I tried out the new installer in the dev branch and it worked! Great work! 😸 

![bild](https://user-images.githubusercontent.com/42991003/102473554-df712a00-4057-11eb-90b4-a0a059553f58.png)
