### ISSUE TITLE
Black screen when pressing SUPER+T

### ISSUE THREAD

**Issue by GeorgeFlorian** [albin-johansson/tactile#51]
Just like the tittle says, I get black screen when I'm trying to use this extension, making this extension unusable.

Ubuntu 22.04.1 LTS
Gnome: 42.4
Windowing system: X11

**Comment by albin-johansson** [comment]
Hi.

Unfortunately, this issue doesn't provide nearly enough information for me to help you. Please try to provide more details, e.g. reproduction steps, screen shots, expected behavior, Tactile version.

**Comment by GeorgeFlorian** [comment]
> Hi.
> 
> Unfortunately, this issue doesn't provide nearly enough information for me to help you. Please try to provide more details, e.g. reproduction steps, screen shots, expected behavior, Tactile version.

Uhm, so the laptop I've been using Tactile on has proven faulty. I will get a new Linux laptop and I will keep using Tactile and report if I encounter any bug.
But in the last days of use, I had no problem with Tactile. I suspect now that there may have been a hardware issue.

But thank you for your fast reply.
